services:
  - type: web
    name: fief
    env: docker
    region: frankfurt
    plan: starter
    domains:
      - fief.wdtk.io
    numInstances: 1
    dockerfilePath: ./fief/Dockerfile
    dockerContext: ./fief
    envVars:
      - key: SECRET
        sync: false
      - key: FIEF_CLIENT_ID
        sync: false
      - key: FIEF_CLIENT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: ROOT_DOMAIN
        value: fief.wdtk.io
      - key: FIEF_DOMAIN
        value: fief.wdtk.io
      - key: CSRF_COOKIE_SECURE
        value: True
      - key: LOGIN_SESSION_COOKIE_SECURE
        value: True
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: FIEF_ADMIN_SESSION_COOKIE_SECURE
        value: True
      - key: ALLOW_ORIGIN_REGEX
        value: https://wdtk\.io
      - key: FORWARDED_ALLOW_IPS
        value: "*"
      - key: DATABASE_TYPE
        value: POSTGRESQL
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString

  - type: redis
    name: redis
    ipAllowList: []
    region: frankfurt
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: database
    ipAllowList: []
    plan: free
    postgresMajorVersion: 14
